### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kathryngauthier** [acgd-webdev-3/music-control-bar#22]
@thomasjbradley 
When I go check this is the only error
" Line 55: Expected single space before "{" (block-opening-brace-space-before)"
How do I fix this?

**Comment by thomasjbradley** [comment]
Right here, in your code:
https://github.com/kathryngauthier/music-control-bar/blob/gh-pages/css/main.css#L55

There needs to be a space between `.time-lapsed` and the `{`.

It should look like this:
```css
.time-lapsed {
```
