### ISSUE TITLE
Pull request not showing Details

### ISSUE THREAD

**Issue by pamelaazzi** [acgd-webdev-3/music-control-bar#54]
@thomasjbradley 

![screen shot 2016-01-20 at 8 29 04 pm](https://cloud.githubusercontent.com/assets/6340293/12468820/e16b454e-bfb4-11e5-86a1-85b76dc993b6.png)

My Pull Request failed but is not showing me any Details.

Why is this happening?

**Comment by thomasjbradley** [comment]
They are having some serious issues right now and are looking into it.

You can follow the status here:
https://www.traviscistatus.com/
